[package]
name = "chameleon"
description = "🦎 Highly customizable Wayland shell"
version = "0.1.0"
edition = "2024"

[dependencies]
chameleon-launcher.workspace = true
chameleon-ipc.workspace = true
chameleon-panel.workspace = true
widgets.workspace = true
notifications.workspace = true

grapes.workspace = true

anyhow.workspace = true
env_logger.workspace = true
log.workspace = true
inotify.workspace = true
futures-util.workspace = true
console-subscriber.workspace = true
dashmap.workspace = true
argh.workspace = true
resolve-path = "0.1.0"
