[package]
name = "chameleon"
description = "🦎 Highly customizable Wayland shell."
version = "0.1.0"
edition = "2024"

[dependencies]
chameleon-cli.workspace = true
chameleon-launcher.workspace = true
chameleon-config.workspace = true
chameleon-ipc.workspace = true
chameleon-panel.workspace = true
chameleon-widgets.workspace = true
chameleon-notifications.workspace = true

grapes.workspace = true

anyhow.workspace = true
env_logger.workspace = true
log.workspace = true
inotify.workspace = true
futures-util.workspace = true
console-subscriber.workspace = true
dashmap.workspace = true
