[package]
name = "chameleon"
version = "0.1.0"
edition = "2024"

[dependencies]
chameleon_shared.workspace = true

anyhow.workspace = true
argh.workspace = true
serde.workspace = true
toml.workspace = true
tokio = { workspace = true, features = ["rt", "macros"] }
tracing.workspace = true
tracing-subscriber.workspace = true
tokio-util.workspace = true
