[workspace]
resolver = "3"
members = ["crates/*"]

[workspace.dependencies]
chameleon_shared = { path = "crates/chameleon-shared" }
chameleon-hyprland = { path = "crates/chameleon-hyprland" }
chameleon-ipc = { path = "crates/chameleon-ipc" }

gtkio = { path = "crates/gtkio" }

argh = "0.1.19"
anyhow = "1.0.102"
inotify = "0.11.0"
log = "0.4.28"
serde = "1.0.228"
toml = "0.9.8"
thiserror = "2.0.18"
serde_json = "1.0.149"
freedesktop-desktop-entry = "0.8.1"
libc = "0.2.186"
nucleo = "0.5.0"
chrono = "0.4.44"
dashmap = "6.1.0"
gtk = { version = "0.11.3", package = "gtk4", features = ["v4_20"] }
layer_shell = { version = "0.8.0", package = "gtk4-layer-shell" }
env_logger = "0.11.8"
futures-util = "0.3.31"

# Tokio stuff
tokio = "1.52.3"
tokio-util = "0.7.18"
console-subscriber = "0.5.0"
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }

[profile.release]
lto = "thin"
