[widgets]
enabled = true

[bar]
enabled = true
thickness = 30
modules_left = ["clock"]
modules_center = ["clock"]
modules_right = ["clock"]

# [bar.battery]
# icons = ["󰂎", "󰁺", "󰁻", "󰁼", "󰁽", "󰁾", "󰁿", "󰂀", "󰂁", "󰂂", "󰁹"]
# name = "BAT1"
# format = "{icon} {charge}%"

[bar.clock]
format = "%a %e %b %H:%M"
