[widgets]
enabled = true

[taskbar]
enabled = true
position = "bottom"
modules_left = []
modules_center = []
modules_right = ["clock"]

[taskbar.battery]
icons = ["󰂎", "󰁺", "󰁻", "󰁼", "󰁽", "󰁾", "󰁿", "󰂀", "󰂁", "󰂂", "󰁹"]
name = "BAT1"
format = "{icon} {charge}%"

[taskbar.clock]
format = "%a %e %b %H:%M"
