[package]
name = "chameleon-launcher"
version = "0.1.0"
edition = "2024"

[dependencies]
chameleon_shared.workspace = true

argh.workspace = true
gtk.workspace = true
gtkio.workspace = true
tokio.workspace = true
layer_shell.workspace = true

freedesktop-desktop-entry.workspace = true
libc.workspace = true
thiserror.workspace = true
nucleo.workspace = true
serde.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
walkdir = "2.5.0"
