[package]
name = "chameleon-launcher"
version = "0.1.0"
edition = "2024"

[dependencies]
chameleon-config.workspace = true
chameleon-ipc.workspace = true
chameleon-core.workspace = true

grapes.workspace = true

freedesktop-desktop-entry.workspace = true
log.workspace = true
libc.workspace = true
thiserror.workspace = true
nucleo.workspace = true
