[package]
name = "chameleon-launcher"
version = "0.1.0"
edition = "2024"

[dependencies]
chameleon-config = { path = "../chameleon-config" }
chameleon-ipc = { path = "../chameleon-ipc" }
chameleon-core = { path = "../chameleon-core" }

grapes.workspace = true

freedesktop-desktop-entry = "0.8.1"
log = "0.4.29"
libc = "0.2.183"
thiserror = "2.0.18"
nucleo = "0.5.0"
