[package]
name = "chameleon-launcher"
version = "0.1.0"
edition = "2024"

[dependencies]
grapes = { path = "../../grapes/grapes" }
grapes-components = { path = "../../grapes/grapes-components" }
chameleon-config = { path = "../chameleon-config" }
chameleon-ipc = { path = "../chameleon-ipc" }
chameleon-core = { path = "../chameleon-core" }
freedesktop-desktop-entry = "0.8.1"
