[package]
name = "chameleon"
description = "🦎 Highly customizable Wayland shell."
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
chrono = "0.4.42"
env_logger = "0.11.8"
grapes = { path = "../../grapes/grapes" }
log = "0.4.28"
chameleon-config = { path = "../chameleon-config" }
chameleon-ipc = { path = "../chameleon-ipc" }
argh = "0.1.13"
inotify = "0.11.0"
futures-util = "0.3.31"
