[package]
name = "chameleon"
description = "🦎 Highly customizable Wayland shell."
version = "0.1.0"
edition = "2024"

[profile.release]
lto = true

[dependencies]
anyhow = "1.0.100"
chrono = "0.4.42"
clap = { version = "4.5.51", features = ["derive"] }
env_logger = "0.11.8"
grapes = { path = "../../grapes/grapes" }
log = "0.4.28"
chameleon-configuration = { path = "../chameleon-configuration" }
