[package]
name = "chameleon-panel"
version = "0.1.0"
edition = "2024"

[dependencies]
chameleon-config.workspace = true
chameleon-ipc.workspace = true
chameleon-core.workspace = true

grapes.workspace = true
grapes_components.workspace = true

chrono.workspace = true
log.workspace = true
dashmap.workspace = true
uuid = { workspace = true, features = ['v4'] }
anyhow.workspace = true
tokio-util.workspace = true
