[package]
name = "chameleon-panel"
version = "0.1.0"
edition = "2024"

[dependencies]
argh.workspace = true
chameleon-ipc.workspace = true
chameleon-hyprland.workspace = true
chameleon_shared.workspace = true
thiserror.workspace = true

gtk.workspace = true
gtkio.workspace = true

tokio.workspace = true
layer_shell.workspace = true

chrono.workspace = true
dashmap.workspace = true
anyhow.workspace = true
tokio-util.workspace = true
suukon = "0.2.0"
serde.workspace = true
pulse = { version = "2.30.1", package = "libpulse-binding" }

tracing.workspace = true
tracing-subscriber.workspace = true
arc-swap = "1.9.1"
sysinfo = "0.39.2"
system-tray = "0.8.6"
