[package]
name = "chameleon-panel"
version = "0.1.0"
edition = "2024"

[dependencies]
chameleon-config.workspace = true
chameleon-ipc.workspace = true
chameleon-core.workspace = true

gtk.workspace = true
gtkio.workspace = true
tokio.workspace = true

grapes.workspace = true
grapes_components.workspace = true

chrono.workspace = true
log.workspace = true
dashmap.workspace = true
uuid = { workspace = true, features = ['v4'] }
anyhow.workspace = true
tokio-util.workspace = true
suukon = "0.2.0"
pulse = { version = "2.30.1", package = "libpulse-binding" }
