[package]
name = "chameleon-core"
version = "0.1.0"
edition = "2024"

[dependencies]
gtk.workspace = true
gtke.workspace = true
gtkio.workspace = true
serde = { workspace = true, features = ["derive", "rc"] }
toml.workspace = true
thiserror.workspace = true
inotify.workspace = true
tracing.workspace = true
futures = "0.3.32"
tracing-subscriber.workspace = true
